- id: doi:10.1038/s41597-024-03931-8
  image: images/publications/scientific-data.svg

- id: doi:10.1145/3657604.3664675
  image: images/publications/las24.png

- id: doi:10.1111/bjet.13505
  image: images/publications/bjet.jpg

- id: doi:10.1145/3636555.3636906
  image: images/publications/lak24.png

- id: doi:10.1145/3636555.3636936
  image: images/publications/lak24.png  

- id: arxiv:2405.14186
  publisher: "Learning Engineering Virtual Institute"
  image: images/publications/levi.jfif

- id: doi:10.35542/osf.io/pvbmt
  publisher : "Learning Engineering Virtual Institute"
  image: images/publications/levi.jfif

- id: doi:10.1145/3593013.3594107
  image: images/publications/facct23.png

- id: isbn:978-3-7799-7718-6
  title: "What can digital trace data tell us about postsecondary students' academic success? An overview of the literature and an illustrative example"
  authors:
    - "Luise von Keyserlingk"
    - "Fani Lauermann"
    - "Renzhe Yu"
    - "Charlott Rubach"
    - "Richard Arum"
  publisher: "Jahrbuch der Schulentwicklung (Band 23)"
  date: 2023-06-21
  link: "https://www.beltz.de/fachmedien/paedagogik/produkte/details/51064-jahrbuch-der-schulentwicklung-band-23.html"
  image: images/publications/jahrbuch.png

- id: doi:10.5281/zenodo.8115691
  authors:
    - "Harshita Chopra"
    - "Yiwen Lin"
    - "Mohammad Amin Samadi"
    - "Jacqueline G. Cavazos"
    - "Renzhe Yu"
    - "Spencer Jaquay"
    - "Nia Nixon"
  publisher: "Proceedings of the 16th International Conference on Educational Data Mining"
  image: images/publications/edm23.png
  
- id: arxiv:2309.12371
  publisher: "Learning Engineering Virtual Institute"
  image: images/publications/levi.jfif

- id: doi:10.35542/osf.io/jtb5n
  publisher: "Learning Engineering Virtual Institute"
  image: images/publications/levi.jfif

- id: doi:10.1145/3491140.3528285
  image: images/publications/las22.png

- id: doi:10.1177/23328584211065725
  date: 2022-03-11
  image: images/publications/aera-open.jpg

- id: doi:10.1371/journal.pone.0276839
  image: images/publications/plos-one.png

- id: doi:10.1145/3430895.3460139
  image: images/publications/las21.jpg

- id: doi:10.18653/V1/2021.NLP4POSIMPACT-1.11
  date: 2021-08-05
  image: images/publications/acl21.png

- title: "How Universities Can Mind the Skills Gap (Higher Education and the Future of Work)"
  date: 2021-04-01
  authors:
    - "Carlos X. Lastra-Anadon"
    - "Subhro Das"
    - "Kush R. Varshney"
    - "Hari Raghavan"
    - "Renzhe Yu"
  publisher: "Center for the Governance of Change, IE University"
  link: https://www.ie.edu/cgc/research/higher-education-future-work/
  image: images/publications/ie-cgc.jpg

- title: "Construction of Weighted Course Co-Enrollment Network"
  date: 2021-04-12
  authors:
    - "Xunfei Li"
    - "Renzhe Yu"
  publisher: "Proceedings of the Workshop on Using Network Science in Learning Analytics: Building Bridges towards a Common Agenda"
  link: https://ceur-ws.org/Vol-2868/article_5.pdf
  image: images/publications/lak21.jpg

- id: doi:10.1007/s11145-020-10081-x
  image: images/publications/r&W.webp

- id: doi:10.1145/3386527.3406755
  image: images/publications/las.png

- id: doi:10.1186/s41239-020-00187-1
  image: images/publications/ethe.jpg

- id: doi:10.3102/0091732X20903304
  image: images/publications/rre.jpg